8-bit SIFT descriptors
terfendail/opencv pull request #11
Opened 2020-07-16 17:50 UTC by Yosshi999

Issue #10 
Simply convert the descriptor matrix to uchar after it is calculated in float32.
To reduce the overhead we will have to modify `calcSIFTDescriptor`. (changing `float*` to `template<typename T>`  may be the simplest solution?)

### Pull Request Readiness Checklist

See details at https://github.com/opencv/opencv/wiki/How_to_contribute#making-a-good-pull-request

- [x] I agree to contribute to the project under OpenCV (BSD) License.
- [x] To the best of my knowledge, the proposed patch is not based on a code under GPL or other license that is incompatible with OpenCV
- [x] The PR is proposed to proper branch
- [x] There is reference to original bug report and related work
- [x] There is accuracy test, performance test and test data in opencv_extra repository, if applicable
      Patch to opencv_extra has the same branch name.
- [x] The feature is well documented and sample code can be built with the project CMake

2020-07-27 22:23 UTC, terfendail requested changes

2020-07-27 22:23 UTC, terfendail commented on modules/features2d/src/sift.simd.hpp
> +    cv::utils::BufferArea area;
It would be better to use the same BufferArea for all temporary locations. Could you please merge it with variables set allocated on `buf`

2020-07-27 22:23 UTC, terfendail commented on modules/features2d/src/sift.simd.hpp
> +    float* dst = dstMat.ptr<float>(row);
Look like the code below should use `rawDst` as well

2020-07-29 13:29 UTC, terfendail approved these changes
I think PR to the main repository could be created

2020-07-31 10:48 UTC, Yosshi999 commented
Created https://github.com/opencv/opencv/pull/18001

2020-07-31 10:48 UTC, closed without merging

2020-07-31 19:02 UTC, tompollok commented
@Yosshi999 Did you make any benchmarks regarding matchin performance and extraction time cost of 8bit vs 32bit? Im just curious if there is a significant difference.

2020-08-02 05:47 UTC, Yosshi999 commented
> Did you make any benchmarks regarding matchin performance and extraction time cost of 8bit vs 32bit? Im just curious if there is a significant difference.

I think its performance and memory usage are not so different because the main calculation part is same.  Of course the size of result descriptor matrix will be reduced to 1/4.
Anyway, I will measure these performances.

2020-08-02 13:57 UTC, Yosshi999 commented
@tompollok 

<details>
<summary>Test cases</summary>
<pre>
feature2d_extract.
  extract/18  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
  extract/19  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
  extract/20  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
feature2d_detectAndExtract.
  detectAndExtract/18  # GetParam() = (SIFT_DEFAULT, "cv/detectors_descriptors_evaluation/images_datasets/leuven/img1.png")
  detectAndExtract/19  # GetParam() = (SIFT_DEFAULT, "stitching/a3.png")
  detectAndExtract/20  # GetParam() = (SIFT_DEFAULT, "stitching/s2.jpg")
</pre>
</details>

CPU features: SSE SSE2 SSE3 *SSE4.1 *SSE4.2 *FP16 *AVX *AVX2 *AVX512-SKX?

Performance   test | 32bit float   (reference) | 8bit unsigned | speed up
-- | -- | -- | --
extract/18 | 53.01 | 52.2 | 1.015517241
extract/19 | 36.8 | 35.72 | 1.030235162
extract/20 | 158.93 | 153.72 | 1.033892792
detectAndExtract/18 | 146.9 | 145.04 | 1.012824049
detectAndExtract/19 | 159.73 | 158.71 | 1.006426816
detectAndExtract/20 | 375.53 | 377.42 | 0.994992316

2020-08-02 15:02 UTC, tompollok commented
Thank you for benchmarking!